apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: monitoring
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
        - name: nginx-prometheus-exporter
          image: nginx/nginx-prometheus-exporter
          args:
            - "-nginx.scrape-uri=http://localhost:80/stub_status"
          ports:
            - containerPort: 9113
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: monitoring
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: prom-exporter
      protocol: TCP
      port: 9113
      targetPort: 9113
  type: NodePort
